import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../app/globals.css";
import MainProvider from "@/providers/MainProvider";
import EditProfileModal from "./(profile)/[user]/EditProfileModal";
import Sidebar from "@/components/layout/Sidebar";
import CreatePostModal from "@/components/layout/CreatePostModal";
import Bottombar from "@/components/home/Bottombar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Instagram - clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MainProvider>
          <CreatePostModal />
          <EditProfileModal />
          <div className="flex justify-between scroll-p-0 ">
            <Sidebar />
            <div className="w-full ">{children}</div>
            <div className="fixed bottom-0 w-full md:hidden ">
              <Bottombar />
            </div>
          </div>
        </MainProvider>
      </body>
    </html>
  );
}
