import React from "react";
import { Metadata } from "next";
import ClientComponent from "./ClientComponent";

interface PageProps {
  params: {
    username: string;
  };
}

// Função para gerar a metadata dinamicamente
export async function generateMetadata({
  params,
}: PageProps): Promise<Metadata> {
  const { username } = params;
  return {
    title: `${username}`,
    description: "Generated by create next app",
  };
}

export default function Page({ params }: { params: { username: string } }) {
  const { username } = params;

  return (
    <div>
      <ClientComponent username={username} />
    </div>
  );
}
