import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "../components/Sidebar";
import Stories from "@/components/Stories";
import Feed from "@/components/Feed";
import Rightbar from "@/components/Rightbar";
import Topbar from "@/components/Topbar";
import Bottombar from "@/components/Bottombar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Instagram",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex justify-between scroll-p-0 ">
        <Sidebar />
        <div className="w-full flex  justify-center ml-0 xl:ml-[244px] 2xl:ml-[335px]">
          <div className="md:w-[630px] w-full mt-0  md:mt-4 border-transparent border">
            <div className="md:hidden mb-5 fixed w-full bg-black top-0 z-[1000000000]">
              <Topbar />
            </div>
            <div className="mt-[70px]">
              <Stories />
            </div>
            <div>
              <Feed />
            </div>
            <div className="fixed bottom-0 w-full md:hidden">
              <Bottombar />
            </div>
          </div>
          <div className="w-[383px] pl-16  border-transparent border mt-9 hidden xl:block">
            <Rightbar />
          </div>
        </div>
      </body>
    </html>
  );
}
